[package]
name = "dhcp_server"
version = "0.1.0"
authors = ["teruya <abas.trace.on@gmail.com>"]
edition = "2018"

[dependencies]
pnet = "0.22.0"
byteorder = "1"
bincode = "1.0.0"
serde_derive = "1.0"
serde = "1.0"